import { MapModel } from './map-model';

export const exampleModel: MapModel = {
    floors: [
        ['floor', 'floor', 'floor', 'floor', 'floor'],
        ['floor', 'floor', 'floor', 'floor', 'floor'],
        ['floor', 'floor', 'floor', 'floor', 'floor'],
        ['floor', 'floor', 'floor', 'floor', 'floor'],
        ['floor', 'floor', 'floor', 'floor', 'floor'],
    ],
    verticalEdges: [
        ['wall', 'empty', 'empty', 'empty', 'empty', 'wall'],
        ['wall', 'wall', 'empty', 'empty', 'door', 'empty'],
        ['wall', 'wall', 'wall', 'empty', 'empty', 'empty'],
        ['wall', 'wall', 'wall', 'empty', 'empty', 'empty'],
        ['door', 'empty', 'empty', 'empty', 'door', 'door'],
    ],
    horizontalEdges: [
        ['wall', 'wall', 'wall', 'wall', 'wall'],
        ['empty', 'door', 'wall', 'wall', 'empty'],
        ['empty', 'empty', 'wall', 'wall', 'empty'],
        ['empty', 'empty', 'empty', 'empty', 'empty'],
        ['empty', 'door', 'empty', 'empty', 'door'],
        ['wall', 'door', 'wall', 'empty', 'empty'],
    ],
    texts: [],
    width: 5,
    height: 5,
};

// https://bardstaleonline.com/bt1/maps/cellar_1
export const wineCellarModel: MapModel = {
    floors: [
        'uuuuuuuuuuuuuuuuuuuuuu',
        'uffffffffffffffffffffu',
        'ufuufuuuufffuuuuuuuufu',
        'uffffuufufffuufffffufu',
        'ufuuffffufffuufufufufu',
        'ufuufuffufffuufffffufu',
        'ufuufufuufffuufuffuufu',
        'ufuufufuufffuuffffuufu',
        'ufuufuuuufufuuuuufuufu',
        'uffffffffffffffffffffu',
        'ufffffffufdfuffffffffu',
        'uffffffffffffffffffffu',
        'ufuufuuuufufuuuuuufufu',
        'uffffufuufffuuuuuufufu',
        'ufuufufuufffuufffffufu',
        'ufuufufuufffuufffffufu',
        'uffufffuufffuufffffufu',
        'uffufuuuufffuufffffufu',
        'uffufuuuufffuufffffufu',
        'uffffuuuufffuuuuuuuufu',
        'fffffffffffffffffffffu',
        'ffuuuuuuuuuuuuuuuuuuuu',
    ].map(row =>
        row.split('').map(c => (c === 'f' ? 'floor' : c === 'd' ? 'darkness' : 'unknown')),
    ),
    verticalEdges: [
        'weeeeeeeeeeeeeeeeeeeeew',
        'wweeeeeeeeeeeeeeeeeeeww',
        'wwwwwweewweewweeeeeewww',
        'wwdedwewwweewwweeeewwww',
        'wwwwweewwweewwwwwwwwwww',
        'wwwwwwwdwweewwweeeewwww',
        'wwwewwwwwweewwwwwwwewww',
        'wwwewwwwwweewwweewwewww',
        'wwwwwweewwwwwweeewwewww',
        'wweeeeeeeeeeeeeeeeeeeww',
        'wweeeeeewweewweeeeeeeww',
        'wweeeeeeeeeeeeeeeeeeeww',
        'wwwewweeewwwweeeeewwwww',
        'wwdwdwwweweewweeeewwwww',
        'wwwewwwweweewwwwwwwwwww',
        'wwwewwwweweewwwdeeewwww',
        'wwdwweeweweewwwdeeewwww',
        'wwwwwweeeweewwwdeeewwww',
        'wwwwwweeeweewwwwwwwwwww',
        'wwwewweeeweewweeeeeewww',
        'weeeeeeeeeeeeeeeeeeeeww',
        'weweeeeeeeeeeeeeeeeeeew',
    ].map(row => row.split('').map(c => (c === 'w' ? 'wall' : c === 'd' ? 'door' : 'empty'))),
    horizontalEdges: [
        'wwwwwwwwwwwwwwwwwwwwww',
        'ewwwwwwwwwwwwwwwwwwwwe',
        'eewwewwwweeewwwwwwwwee',
        'eewweeeweeeeeewwwwweee',
        'eewwewwdeeeeeeeweweeee',
        'eeeeeweeeeeeeeeweweeee',
        'eewweeeweeeeeeeweeweee',
        'eeweeeeeeeeeeeeweeeeee',
        'eeeeeeweeeweeewwweeeee',
        'eewwewwwwewewwwwwdwwee',
        'eeeeeeeeweeeweeeeeeeee',
        'eeeeeeeeweeeweeeeeeeee',
        'eewwewwwwewewwwwwwdwee',
        'eewweeweeeweewwwwweeee',
        'eewweeeeeeeeeewwwweeee',
        'eeeeeeeeeeeeeeedddeeee',
        'eeweeweeeeeeeeweeeeeee',
        'eeeeewweeeeeeeweeeeeee',
        'eeeeeeeeeeeeeeeddddeee',
        'eeeweeeeeeeeewwwwwweee',
        'wewwewwwweeewwwwwwwwee',
        'eewwwwwwwwwwwwwwwwwwwe',
        'wwwwwwwwwwwwwwwwwwwwww',
    ].map(row => row.split('').map(c => (c === 'w' ? 'wall' : c === 'd' ? 'door' : 'empty'))),
    texts: [
        { x: 10, y: 10, value: '↻' },
        { x: 0, y: 21, value: '⇧' },
        { x: 7, y: 3, value: '⇩' },
        { x: 16, y: 5, value: 'trap' },
        { x: 1, y: 20, value: '1' }, // This is the wine cellar of the Scarlet Bard. The air is musty with old wine.
        { x: 17, y: 9, value: '2' }, // Fine wines - 10 years or older. For regular customers only.
        { x: 18, y: 11, value: '3' }, // Rare wines - 50 years and older. Keep out!
    ],
    width: 22,
    height: 22,
};
